name: diar_tunis
description: "Cultural tourism application for Tunisia."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP and API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI and Navigation
  go_router: ^12.1.3
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  
  # Firebase (optional for push notifications)
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  dartz: ^0.10.1
  fl_chart: ^1.0.0
  get_it: ^8.2.0
  internet_connection_checker_plus: ^2.2.0
  injectable: ^2.5.1
  provider: ^6.1.5


  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

   # Code Generation
  build_runner: ^2.5.4
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
